  try {
export const main = async () => {
  } catch (err) {
    console.log(err);
  }
};
